### ISSUE TITLE
The hypar.json cannot be deserialized.

### ISSUE THREAD

**Issue by ikeough** [hypar-io/sdk#67]
```
Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Could not create an instance of type Hypar.Configuration.ParameterData. Type is an interface or abstract class and cannot be instantiated. Path 'parameters.height.min', line 9, position 18.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Hypar.Commands.NewCommand.UpdateHyparJson(String directory, String name) in /Users/ikeough/Documents/hypar/sdk/csharp/src/cli/Commands/NewCommand.cs:line 77
   at Hypar.Commands.NewCommand.New(String functionName) in /Users/ikeough/Documents/hypar/sdk/csharp/src/cli/Commands/NewCommand.cs:line 53
   at Hypar.Program.Main(String[] args) in /Users/ikeough/Documents/hypar/sdk/csharp/src/cli/Program.cs:line 65
```

**Comment by ikeough** [comment]
This error was caused because I did not use the `HyparConfig.FromJson(....)` method which uses the correct converters.
